[Segmentation] Added generalized dice score metric
Lightning-AI/torchmetrics pull request #1090
Opened 2022-06-15 16:43 UTC by jlcsilva

## What does this PR do?

Fixes #1089 . Didn't manage to make it work for multidimensional multilabel scenarios. However, that shouldn't a very common use case.

## Before submitting

- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [x] Did you write any new **necessary tests**?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2022-06-17 13:31 UTC, Borda commented
I beilve that this shall be automatically resolved in cmd by `git merge upstream/master`

2022-06-20 09:08 UTC, Borda commented
@jlcsilva shall be resolved now, pls check if I did not make a mistake... :rabbit:

2022-06-22 16:09 UTC, jlcsilva commented
> @jlcsilva shall be resolved now, pls check if I did not make a mistake... 🐰

Seems ok to me. 

Also, I know why the tests are failing, but I'm unsure about what to do. In the file tests/unittests/classification/inputs.py
I changed the data type of some input tensors, such as _input_binary, from int to float, to match the description [here](https://torchmetrics.readthedocs.io/en/latest/pages/classification.html#input-types). Since the tests are failing, I'm not sure what's wrong, the documentation or the code. Any thoughts from someone with a better overall view of the repo?

2022-06-28 11:18 UTC, SkafteNicki commented
Hi @jlcsilva, when looking at the changes in the PR there also seems to be some changes to other metrics. Any particular reason for this?

2022-06-28 21:22 UTC, jlcsilva commented
> Hi @jlcsilva, when looking at the changes in the PR there also seems to be some changes to other metrics. Any particular reason for this?

In the StatScore class I added the None option for the reduce argument, which I needed for my generalized dice score implementation, and changed its documentation and that of its subclasses accordingly. Additionally, I corrected some typos and added some missing information to these classes' documentation. 

Finally, I changes the data type of some test inputs to match that in the general input type documentation page, and added new multidimensional input tensors. To me, this seems to be what is making the code fail the tests. Currently, I'm out of office, but I'll check it as soon as I go back to work

2022-06-29 11:58 UTC, Borda commented on src/torchmetrics/classification/generalized_dice.py
> +            Determines whether the input is multidim or not. Defaults to True.
```suggestion
            Determines whether the input is ``multidim`` or not.
```

2022-06-29 11:58 UTC, Borda commented on src/torchmetrics/classification/generalized_dice.py
> +            numerator is also 0, and 0 otherwise. Defaults to None.
```suggestion
            numerator is also 0, and 0 otherwise.
```

2022-06-29 11:58 UTC, Borda commented on src/torchmetrics/functional/classification/generalized_dice.py
> +        fn[..., ignore_index]
this seems to be void

2022-06-29 11:58 UTC, Borda commented on src/torchmetrics/functional/classification/generalized_dice.py
> +            numerator is also 0, and 0 otherwise. Defaults to None.
```suggestion
            numerator is also 0, and 0 otherwise.
```

2022-06-29 11:58 UTC, Borda commented on src/torchmetrics/functional/classification/generalized_dice.py
> +            Determines whether the input is multidim or not. Defaults to True.
```suggestion
        multiclass:
            Determines whether the input is multiclass (if True) or multilabel (if False).

        multidim:
            Determines whether the input is multidim or not.
```
duplicated from func signature

2022-06-29 11:58 UTC, Borda commented on src/torchmetrics/classification/generalized_dice.py
> +            Determines whether the input is multiclass (if True) or multilabel (if False). Defaults to True.
```suggestion
            Determines whether the input is multiclass (if True) or multilabel (if False).
```

2022-06-29 11:58 UTC, Borda commented on tests/classification/test_generalized_dice_score.py
> +def _sk_generalized_dice(
I do not see any import or use of scikit-learn so why do you name it this way?

2022-06-29 12:00 UTC, Borda commented on src/torchmetrics/classification/generalized_dice.py
> +            Determines whether the input is multidim or not. Defaults to True.
```suggestion
            Determines whether the input is multidim or not.
```

2022-08-05 12:52 UTC, SkafteNicki requested changes
Hi @jlcsilva,
Sorry for the long delay. We are currently doing a major refactor of the classification package #1001 and are therefore putting this PR on hold for now. When the refactor is done we will mix merge conflicts and afterwards focus on getting your awesome work merged :)

2022-08-05 13:17 UTC, jlcsilva commented
Hey @SkafteNicki,
No problem! I've also been away, so wasn't able to help. I noticed the changes when I came back and pulled the repo again. I'm actually a bit busy today and next week, but let me know if there is something I can help with :)

2022-09-13 22:18 UTC, Borda commented
@jlcsilva @SkafteNicki, mind checking the collisions after the refactor was merged... :)

2022-10-05 10:10 UTC, Borda commented
@jlcsilva @stancld, mind checking the collisions after the refactor was merged... :otter:

2022-10-05 10:19 UTC, stancld commented
@Borda I'll do rebase now.

2022-10-05 10:28 UTC, stancld commented
ℹ️ It will be needed to add test cases after refactoring tests as a part of the classification refactor.

2022-11-05 20:57 UTC, japui-coder requested changes
tests/integrations/test_lightning.py

2022-11-06 12:25 UTC, SkafteNicki commented
Going to take over this PR now so we hopefully can land it within the next week :]

2022-12-23 05:03 UTC, Borda commented
> Going to take over this PR now so we hopefully can land it within the next week :]

hi @SkafteNicki how is it going here? :)

2023-01-30 16:16 UTC, Borda commented
@justusschock, how much need to be done? :chipmunk:

2023-02-20 20:58 UTC, Borda approved these changes
except https://github.com/Lightning-AI/metrics/pull/1090#discussion_r909536311it looks good to me

2023-02-20 20:58 UTC, Borda commented on src/torchmetrics/classification/dice.py
> +    .. deprecated:: v0.10
```suggestion
    .. deprecated:: v0.12
```

2023-02-20 20:58 UTC, Borda commented on src/torchmetrics/classification/dice.py
> +        The `Dice` module was deprecated in v0.10 and will be removed in v0.11. Use `F1Score` module instead which
```suggestion
        The `Dice` module was deprecated in v0.12 and will be removed in v0.13. Use `F1Score` module instead which
```

2023-02-20 20:58 UTC, Borda commented on src/torchmetrics/classification/dice.py
> +            "The `dice` function was deprecated in v0.10 and will be removed in v0.11. Use `f1score` function instead"
```suggestion
            "The `dice` function was deprecated in v0.12 and will be removed in v0.13. Use `f1score` function instead"
```

2023-02-20 20:58 UTC, Borda commented on src/torchmetrics/classification/generalized_dice.py
> +        >>> target = torch.tensor([1, 1, 2, 0])
```suggestion
        >>> from torch import tensor
        >>> from torchmetrics import GeneralizedDiceScore
        >>> preds = tensor([2, 0, 2, 1])
        >>> target = tensor([1, 1, 2, 0])
```

2023-02-20 20:58 UTC, Borda commented on src/torchmetrics/functional/classification/generalized_dice.py
> +        tensor(0.3478)
```suggestion
```
protected does not need examples

2023-02-20 20:58 UTC, Borda commented on src/torchmetrics/functional/classification/generalized_dice.py
> +        >>> target = torch.tensor([1, 1, 2, 0])
```suggestion
        >>> from torch import tensor
        >>> from torchmetrics.functional import generalized_dice_score
        >>> preds = tensor([2, 0, 2, 1])
        >>> target = tensor([1, 1, 2, 0])
```

2023-08-23 21:11 UTC, Borda commented
@jlcsilva, any chance you could work on this one, in particular, add some tests... :flags:

2024-01-09 13:13 UTC, Borda commented
seems we hit some internal Gh issue, will be restarted later...

2024-04-23 08:54 UTC, SkafteNicki approved these changes

2024-04-23 09:31 UTC, justusschock approved these changes

2024-04-23 11:16 UTC, Borda approved these changes
So happy to see it landing 🤩

2024-04-23 11:53 UTC, merged