Drop python 3.7 support
Lightning-AI/torchmetrics pull request #1640
Opened 2023-03-21 13:36 UTC by SkafteNicki

## What does this PR do?

Python 3.7 is blocking some other PRs:
https://github.com/Lightning-AI/metrics/pull/1636
https://github.com/Lightning-AI/metrics/pull/1570
and since the security support for 3.7 is soon ending, I think we can drop it.

Additionally, we are soon going to add python 3.11 support:
https://github.com/Lightning-AI/metrics/pull/1613

<details>
  <summary>Before submitting</summary>

- [ ] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

2023-03-21 14:21 UTC, akihironitta approved these changes

2023-03-21 14:24 UTC, Borda requested changes
let's wait for #1613

2023-03-21 18:08 UTC, Borda approved these changes

2023-03-28 19:12 UTC, stancld approved these changes

2023-03-30 06:12 UTC, SkafteNicki commented
@Borda now the only problem that seems to remain is that the docker image used for the "old" build on azure still uses python 3.7 and not 3.8.
There is a weird downgrade in the 1.9 image reported here:
https://github.com/pytorch/pytorch/issues/60932
and here is a full list of python version for each image:
https://github.com/pytorch/pytorch/issues/73714#issuecomment-1423557777

2023-04-03 17:36 UTC, merged