New metric: Perceptual Path Length
Lightning-AI/torchmetrics pull request #1939
Opened 2023-07-25 15:09 UTC by SkafteNicki

## What does this PR do?

Fixes #1933

<details>
  <summary>Before submitting</summary>

- [ ] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/torchmetrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

----
:books: Documentation preview :books:: https://torchmetrics--1939.org.readthedocs.build/en/1939/

2023-08-03 18:08 UTC, Borda approved these changes

2023-08-03 18:08 UTC, Borda commented on requirements/image.txt
> +torch-fidelity @ git+https://github.com/toshas/torch-fidelity@master
note that this req. will not be listed in package dependency if installed from PyPI

2023-08-04 13:29 UTC, justusschock approved these changes

2023-08-04 17:46 UTC, Borda commented on requirements/image.txt
> +torch-fidelity @ git+https://github.com/toshas/torch-fidelity@master
Yes, but what do you have in mind, even prevent PR to be merged with this dependency?

2023-08-04 18:17 UTC, Borda commented on requirements/image.txt
> +torch-fidelity @ git+https://github.com/toshas/torch-fidelity@master
ref: https://github.com/toshas/torch-fidelity/issues/53
cc: @JustinGoheen

2023-08-04 18:20 UTC, Borda requested changes
the dependency issue https://github.com/Lightning-AI/torchmetrics/pull/1939#discussion_r1283550803 would prevent user from even using the remaining metrics based on `torch-fidelity` so lets restore PyPI dependency and set this master for testing?

2023-08-08 09:51 UTC, SkafteNicki commented
@Borda, @justusschock please re-review. After a second look at this, we already had a lot of the needed functionality already, so torch-fidelity is no longer needed for the implementation (only testing). A bit of code needed to be copied, but I have linked where needed to original implementation.

2023-08-08 11:23 UTC, SkafteNicki commented
> > After a second look at this, we already had a lot of the needed functionality already, so torch-fidelity is no longer needed for the implementation (only testing). A bit of code needed to be copied, but I have linked where needed to original implementation.
> 
> I am fine with the code, my only concern is the dependency, can we somehow use the released package? what we really need form the master branch?

It's no longer a dependency of this metric, only torchvision is needed.

But we need it for testing to compare against. And we specific need master because the addition of PPL in torch-fidelity happened after latest release

2023-08-08 13:29 UTC, Borda approved these changes

2023-08-09 09:33 UTC, merged