Fix the dependencies of LPIPS metric
Lightning-AI/torchmetrics pull request #2230
Opened 2023-11-21 18:36 UTC by tanguymagne

## What does this PR do?

This PR doesn't solve any issue, as it is a very small fix.

Since #1575, the LPIPS metric does not rely anymore on the third-party package [PerceptualSimilarity](https://github.com/richzhang/PerceptualSimilarity) but now relies on torchvision. The changes were not reflected entirely in the doc and in the tests. 

<details>
  <summary>Before submitting</summary>

- [x] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/torchmetrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**? --> Not necessary. 

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

2023-11-21 18:44 UTC, Borda commented on requirements/image.txt
> -lpips <=0.1.4
This needs to go to image_test.txt

2023-11-21 18:46 UTC, Borda requested changes
this does not seems to be right, check: https://github.com/Lightning-AI/torchmetrics/blob/bcf7867020f5893258d0fedba7aaa16aee6505ca/tests/unittests/image/test_lpips.py#L19

2023-11-21 21:29 UTC, tanguymagne commented
I have made the requested changes. I hope I understood correctly what was requested.
I am wondering whether or not it is a problem to have a dependency on the unmaintained third-party package lpips for testing ?

2023-11-23 09:10 UTC, SkafteNicki approved these changes

2023-11-23 16:34 UTC, awaelchli approved these changes

2023-11-25 18:57 UTC, merged