fix Bug in BertScore calculation: pred target misalignment
Lightning-AI/torchmetrics pull request #2347
Opened 2024-02-03 16:34 UTC by gxy-gxy

## What does this PR do?

Fixes bug in BertScore cal.
This pull request addresses a bug identified in the BertScore calculation within the TextDataset class in `src/torchmetrics/functional/text/helper_embedding_metric.py`.
The class is designed with a preprocess function automatically sorts input text by length to optimize batch encoding efficiency. However, this behavior introduces an issue during the BertScore calculation process, as predictions (preds) and targets (targets) are initialized in separate datasets. This results in a mismatched ordering of text pairs, which is problematic given the pairwise nature of BertScore's calculation. To ensure accurate scoring, it is critical to re-align the datasets to their original order before computing the scores. The proposed fix involves ensuring that the datasets for predictions and targets are processed in a way that maintains their original pairing throughout the calculation process.

Here is the fixed code:
``` 
preds_embeddings = preds_embeddings[preds_loader.dataset.sorting_indices]
target_embeddings = target_embeddings[target_loader.dataset.sorting_indices]
```

This change is essential for preserving the integrity of the BertScore evaluation, ensuring that each prediction is accurately compared against its corresponding target.

2024-02-03 16:40 UTC, gxy-gxy commented
Here is the test code:
```
from torchmetrics.text.bert import BERTScore

score_model = BERTScore(model_name_or_path='roberta-large', batch_size=2)

text1 = [ "Claim A from machine", "Claim A from machine"]
text2 = ["Claim A from machine", "Claim B"]
similarities = score_model(text1, text2)
print(similarities)
```

2024-03-15 18:21 UTC, Borda commented
@stancld could you help here, pls?

2024-05-06 19:18 UTC, baskrahmer reviewed
Good catch! I can reproduce the bug using your test code snippet. Although the actual metric values seem to be correct, the ordering is not always valid.

It might be nice to somehow integrate this case with the current test suite. E.g. an assertation that reversing the targets/preds also reverses the scores.

2024-05-19 02:48 UTC, gxy-gxy commented on src/torchmetrics/functional/text/bert.py
> +    target_embeddings = target_embeddings[target_loader.dataset.sorting_indices]
> I'm pretty sure the IDF factors also need to be unsorted too

Thanks for your suggestion, I will fix it soon.

2024-07-15 15:53 UTC, Borda commented on src/torchmetrics/functional/text/bert.py
> +    target_embeddings = target_embeddings[target_loader.dataset.sorting_indices]
@gxy-gxy how id it going, will you have time to update it?

2024-07-16 10:46 UTC, Borda commented
> Here is the test code:
> 
> ```python
> from torchmetrics.text.bert import BERTScore
> 
> score_model = BERTScore(model_name_or_path='roberta-large', batch_size=2)
> 
> text1 = [ "Claim A from machine", "Claim A from machine"]
> text2 = ["Claim A from machine", "Claim B"]
> similarities = score_model(text1, text2)
> print(similarities)
> ```

@gxy-gxy can you pls add it as a test?

2024-07-16 11:21 UTC, Borda requested changes
https://github.com/Lightning-AI/torchmetrics/pull/2347#issuecomment-2230588194

2024-07-16 11:31 UTC, gxy-gxy commented on src/torchmetrics/functional/text/bert.py
> +    target_embeddings = target_embeddings[target_loader.dataset.sorting_indices]
hello， I have fixed it.

2024-07-19 14:01 UTC, baskrahmer approved these changes
LGTM! Thanks for the addition

2024-07-19 16:02 UTC, Borda commented
@baskrahmer, would mind also adding an entry to the changelog?

2024-07-19 16:40 UTC, merged