Fix incorrect caching of MetricCollection
Lightning-AI/torchmetrics pull request #2571
Opened 2024-05-28 23:40 UTC by relativityhd

## What does this PR do?

Fixes  #2570. Also provides a better test for #2211. A somewhat larger change is that for this fix (especially the testcases) the compute method needs to return deepcopied values.

<details>
  <summary>Before submitting</summary>

- [ ] Was this **discussed/agreed** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/torchmetrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [x] Did you write any new **necessary tests**?

</details>

<details>
  <summary>PR review</summary>

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

</details>

## Did you have fun?

Make sure you had fun coding 🙃

2024-05-29 05:07 UTC, Borda approved these changes
Let's add chlog entry

2024-05-30 12:05 UTC, SkafteNicki approved these changes

2024-05-31 08:20 UTC, Borda commented
@SkafteNicki this is everywhere: `RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment`

2024-05-31 09:20 UTC, SkafteNicki requested changes
we need to make this work without deepcopy of the values

2024-05-31 09:20 UTC, SkafteNicki commented on src/torchmetrics/metric.py
> +                return deepcopy(self._computed)
this is definitely messing with all other code

2024-05-31 09:20 UTC, SkafteNicki commented on src/torchmetrics/metric.py
> +            return deepcopy(value)
this is definitely messing with all other code

2024-05-31 11:25 UTC, SkafteNicki approved these changes
Okay, changing the `deepcopy` to `clone` works out. Thanks for the contribution!

2024-06-01 16:13 UTC, merged